drop table Notification;
drop table Non_visitor;
drop table Visitor;
drop table Citation;
drop table Permit;
drop table Spaces;
drop table Parking_Lots;
drop sequence CITATION_SEQ;
drop sequence NOTIFICATION_SEQ;